[custom]
;解决DNS泄露，无分流群组
ruleset=🎯 家庭直连,clash-classic:https://raw.githubusercontent.com/Gavinlol/Openclash-rules/main/Gavin-Home-Direct-3.yaml
ruleset=🌍 国外流量,clash-classic:https://raw.githubusercontent.com/Gavinlol/Openclash-rules/main/Outside.yaml
ruleset=👨‍💻 GitHub,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.yaml
ruleset=📺 TVB,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TVB/TVB.yaml
ruleset=🎥 流媒体,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.yaml 
# ruleset=🎥 流媒体,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AppleTV/AppleTV.yaml
ruleset=🐹 DisneyPlus,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Disney/Disney.yaml 
ruleset=🤖 AI,clash-classic:https://raw.githubusercontent.com/Gavinlol/Openclash-rules/main/OpenAI.yaml
ruleset=🤖 AI,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Claude/Claude.yaml
ruleset=🤖 AI,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Gemini/Gemini.yaml
ruleset=Ⓜ️ 微软服务,clash-classic:https://raw.githubusercontent.com/Gavinlol/Openclash-rules/main/Copilot.yaml
ruleset=Ⓜ️ 微软服务,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.yaml
# Apple 美国代理
ruleset=🍎 苹果代理,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AppleMusic/AppleMusic.yaml
ruleset=🍎 苹果代理,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AppleTV/AppleTV.yaml
ruleset=🍎 苹果代理,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AppleNews/AppleNews.yaml
ruleset=🍎 苹果代理,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AppleProxy/AppleProxy.yaml

# Apple 国内直连
ruleset=🍎 苹果直连,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AppStore/AppStore.yaml
ruleset=🍎 苹果直连,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.yaml
ruleset=🍎 苹果直连,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AppleDaily/AppleDaily.yaml
ruleset=🍎 苹果直连,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AppleFirmware/AppleFirmware.yaml
ruleset=🍎 苹果直连,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AppleHardware/AppleHardware.yaml
ruleset=🍎 苹果直连,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AppleID/AppleID.yaml
ruleset=🍎 苹果直连,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AppleMail/AppleMail.yaml

ruleset=🎥 流媒体,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AmazonPrimeVideo/AmazonPrimeVideo.yaml
ruleset=🎥 流媒体,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/HBOHK/HBOHK.yaml
ruleset=🎥 流媒体,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/HBOAsia/HBOAsia.yaml
ruleset=🎥 流媒体,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/HBOUSA/HBOUSA.yaml
ruleset=🏦 HK Bank,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BOC/BOC.yaml
ruleset=🏦 HK Bank,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/HSBC/HSBC.yaml
ruleset=🏦 HK Bank,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/HangSeng/HangSeng.yaml
ruleset=🎮 游戏平台,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Epic/Epic.yaml
ruleset=🎮 游戏平台,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Origin/Origin.yaml
ruleset=🎮 游戏平台,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Sony/Sony.yaml
ruleset=🎮 游戏平台,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PlayStation/PlayStation.yaml
ruleset=🎮 游戏平台,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Steam/Steam.yaml
ruleset=🎮 游戏平台,clash-classic:https://raw.githubusercontent.com/Gavinlol/Openclash-rules/main/Nintendo.yaml
;ruleset=🎮 游戏平台,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Nintendo/Nintendo.yaml
;ruleset=🤖 AI,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.yaml
;ruleset=🤖 AI,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Copilot/Copilot.yaml
ruleset=🚀 节点选择,[]DOMAIN-SUFFIX,xn--ngstr-lra8j.com
ruleset=🚀 节点选择,[]DOMAIN-SUFFIX,services.googleapis.cn
ruleset=🚀 节点选择,clash-classic:https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/GoogleCNProxyIP.yaml

ruleset=DIRECT,clash-classic:https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/LocalAreaNetwork.yaml
ruleset=DIRECT,clash-classic:https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/UnBan.yaml
ruleset=DIRECT,clash-classic:https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ChinaDomain.yaml
ruleset=DIRECT,clash-classic:https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ChinaMedia.yaml
;ruleset=REJECT,clash-classic:https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanAD.yaml
;ruleset=REJECT,clash-classic:https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanProgramAD.yaml
;ruleset=DIRECT,clash-ipcidr:https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ChinaCompanyIp.yaml
;ruleset=DIRECT,clash-ipcidr:https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ChinaIp.yaml
ruleset=DIRECT,clash-classic:https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/ChinaIpV6.list
ruleset=DIRECT,[]GEOIP,CN,no-resolve
ruleset=🚀 节点选择,[]FINAL

;策略组定义
custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`[]DIRECT`[]🇭🇰 香港自动`[]🇺🇲 美国自动`[]🇯🇵 日本自动`[]🇸🇬 新加坡自动`[]🔯 香港故转`[]🔯 美国故转`[]🇭🇰 香港节点`[]🇺🇲 美国节点`[]🇯🇵 日本节点`[]🇸🇬 新加坡节点`.*
custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🎯 家庭直连`select`[]DIRECT`[]🇭🇰 香港节点`
custom_proxy_group=🍎 苹果直连`select`[]DIRECT`
custom_proxy_group=🏦 HK Bank`select`[]DIRECT`
custom_proxy_group=🌍 国外流量`select`[]🇭🇰 香港自动`[]🇺🇲 美国自动`[]🇯🇵 日本自动`[]🇸🇬 新加坡自动`[]🔯 香港故转`[]🔯 美国故转`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 新加坡节点`[]🚁 自建节点`[]DIRECT`
custom_proxy_group=👨‍💻 GitHub`select`[]♻️ 自动选择`[]DIRECT`[]🇭🇰 香港自动`[]🇺🇲 美国自动`[]🇯🇵 日本自动`[]🇸🇬 新加坡自动`[]🔯 香港故转`[]🔯 美国故转`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 新加坡节点`[]🚁 自建节点`[]DIRECT`
custom_proxy_group=🍎 苹果代理`select`[]🇭🇰 香港自动`[]🇺🇲 美国自动`[]🇯🇵 日本自动`[]🇸🇬 新加坡自动`[]🔯 香港故转`[]🔯 美国故转`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 新加坡节点`[]🚁 自建节点`[]DIRECT`
custom_proxy_group=Ⓜ️ 微软服务`select`[]🇭🇰 香港自动`[]🇺🇲 美国自动`[]🇯🇵 日本自动`[]🇸🇬 新加坡自动`[]🔯 香港故转`[]🔯 美国故转`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 新加坡节点`[]🚁 自建节点`[]DIRECT`
custom_proxy_group=📺 TVB`select`[]🇭🇰 香港自动`[]🇺🇲 美国自动`[]🇯🇵 日本自动`[]🇸🇬 新加坡自动`[]🔯 TVB故转`[]🔯 香港故转`[]🇭🇰 香港节点`[]DIRECT`
custom_proxy_group=🎥 流媒体`select`[]🇭🇰 香港自动`[]🇺🇲 美国自动`[]🇯🇵 日本自动`[]🇸🇬 新加坡自动`[]🔯 香港故转`[]🔯 美国故转`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 新加坡节点`[]🚁 自建节点`[]DIRECT`
custom_proxy_group=🐹 DisneyPlus`select`[]🇭🇰 香港自动`[]🇺🇲 美国自动`[]🇯🇵 日本自动`[]🇸🇬 新加坡自动`[]🔯 香港故转`[]🔯 美国故转`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 新加坡节点`[]🚁 自建节点`[]DIRECT`
custom_proxy_group=🤖 AI`select`[]🇭🇰 香港自动`[]🇺🇲 美国自动`[]🇯🇵 日本自动`[]🇸🇬 新加坡自动`[]🔯 香港故转`[]🔯 美国故转`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 新加坡节点`[]🚁 自建节点`[]DIRECT`
custom_proxy_group=🎮 游戏平台`select`(Game|游戏|遊戲轉換)

;自动化切换策略组定义，测速间隔300s,timeout=0,tolerance=100ms,剔除低速节点
custom_proxy_group=🇭🇰 香港自动`url-test`(?=.*(香港))^((?!(Lil|US|家宽|Game|游戏|遊戲|遊戲專用|遊戲轉換|剩余|流量|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x)).)*$`http://www.gstatic.com/generate_204`300,,100
custom_proxy_group=🇺🇲 美国自动`url-test`(?=.*(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States))^((?!(Lil|家宽|Game|游戏|遊戲|遊戲專用|遊戲轉換|剩余|流量|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x)).)*$`http://www.gstatic.com/generate_204`300,,100
custom_proxy_group=🇯🇵 日本自动`url-test`(?=.*(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan))^((?!(Lil|家宽|Game|游戏|遊戲|遊戲專用|遊戲轉換|剩余|流量|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x)).)*$`http://www.gstatic.com/generate_204`300,,100
custom_proxy_group=🇸🇬 新加坡自动`url-test`(?=.*(新加坡|坡|狮城|SG|Singapore))^((?!(Lil|家宽|Game|游戏|遊戲|遊戲專用|遊戲轉換|剩余|流量|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x)).)*$`http://www.gstatic.com/generate_204`300,,100

custom_proxy_group=🇭🇰 香港节点`select`(?=.*(香港))^((?!(US|家宽|Game|游戏|遊戲轉換|剩余|流量|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x)).)*$
custom_proxy_group=🇺🇲 美国节点`select`(?=.*(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States))^((?!(US|家宽|Game|游戏|遊戲轉換|剩余|流量|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x)).)*$
custom_proxy_group=🇯🇵 日本节点`select`(?=.*(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan))^((?!(US|家宽|Game|游戏|遊戲轉換|剩余|流量|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x)).)*$
custom_proxy_group=🇸🇬 新加坡节点`select`(?=.*(新加坡|坡|狮城|SG|Singapore))^((?!(US|家宽|Game|游戏|遊戲轉換|剩余|流量|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x)).)*$
custom_proxy_group=🚁 自建节点`select`(自建|gavinlol|BWG|hk-vmess|HY|海晏河清|backup|_)
custom_proxy_group=🔯 香港故转`fallback`(?=.*(香港))^((?!(US|家宽|Game|游戏|遊戲轉換|剩余|流量|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x)).)*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🔯 美国故转`fallback`(?=.*(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States))^((?!(US|家宽|Game|游戏|遊戲轉換|剩余|流量|2.0|2倍|2x|3.0|3倍|3x|4.0|4倍|4x)).)*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🔯 TVB故转`fallback`!!GROUPID=!1!!(香港)`http://www.gstatic.com/generate_204`300,,50

;启用自定义规则集
enable_rule_generator=true
overwrite_original_rules=true

